### PR TITLE
Internal PR for review: migration of base_changeset (ERP-3175)

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by MrGigSolutions — CHANGES_REQUESTED** [review]
I suspect the original form is not updated when you apply a change through the change popover: I changed a field from Hello to Hello2, then clicked the popover and in it the green check mark. It still showed Hello. Then when I changed it to Hello2 and pressed the save button, no additional changeset was created, but the value still shows Hello.

**Comment by StefanRijnhart** [comment]
Ah no I see it.

**Comment by StefanRijnhart** [comment]
Please try again.

**Comment by MrGigSolutions** [comment]
What if we add a field to the change set rule that allows us to indicate on what label we want to show the popover? You can make it optional, but that would allow us to at least specify a place where the changeset button could be seen.

**Pull request merged**
